-- Generated starter content. Run after schema.sql.

insert into public.tours (slug,title,category,duration,price_from,image,excerpt,highlights,includes,itinerary,featured,sort) values ('essential-sri-lanka-7-days','Essential Sri Lanka','Multi-Day','7 days · 6 nights',690,'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=2200&q=80','The island''s greatest hits in one graceful week — ancient rock fortresses, sacred Kandy, the famous highland train, a Yala safari and a golden south-coast finale.','["Sunrise climb of Sigiriya Rock Fortress","Temple of the Sacred Tooth Relic, Kandy","First-class seats on the Kandy–Ella railway","Private leopard safari in Yala","Galle Fort at golden hour"]'::jsonb,'["Private A/C vehicle & chauffeur-guide throughout","All fuel, parking, and driver accommodation","Airport pickup & drop-off","Bottled water daily","24/7 WhatsApp support"]'::jsonb,'[{"day":"Day 1","title":"Arrival → Sigiriya","detail":"Meet at Bandaranaike Airport and glide into the Cultural Triangle. Evening village walk and welcome dinner beneath the rock."},{"day":"Day 2","title":"Sigiriya & Dambulla","detail":"Beat the heat with a sunrise ascent of the Lion Rock, then the painted cave temples of Dambulla. Optional Minneriya elephant safari at dusk."},{"day":"Day 3","title":"Kandy","detail":"Spice gardens and a temple ceremony at the Sacred Tooth Relic, with an evening stroll around Kandy Lake."},{"day":"Day 4","title":"The Highland Railway → Ella","detail":"Reserved seats on the world''s most beautiful train ride while your driver carries the luggage ahead. Sunset at Little Adam''s Peak."},{"day":"Day 5","title":"Ella → Yala","detail":"Nine Arch Bridge at first light, Rawana Falls, then south to the safari gates. Evening at leisure."},{"day":"Day 6","title":"Yala Safari → Galle","detail":"Dawn game drive in leopard country, then the coastal road west to the ramparts of Galle Fort."},{"day":"Day 7","title":"Beach morning → Departure","detail":"A final swim on the south coast before a comfortable transfer to the airport or your next stay."}]'::jsonb,true,0) on conflict (slug) do nothing;
insert into public.tours (slug,title,category,duration,price_from,image,excerpt,highlights,includes,itinerary,featured,sort) values ('grand-island-circuit-14-days','Grand Island Circuit','Multi-Day','14 days · 13 nights',1390,'https://images.unsplash.com/photo-1505142468610-359e7d316be0?auto=format&fit=crop&w=1600&q=80','The complete Sri Lanka — ancient kingdoms, misty tea estates, two contrasting safaris, whale-rich seas and slow days on the island''s finest beaches.','["Anuradhapura & Polonnaruwa ancient cities","Sigiriya and the Cultural Triangle","Tea-estate stay in Nuwara Eliya","Yala + Udawalawe twin safaris","Whale watching in Mirissa (in season)","Galle Fort, Unawatuna & hidden south-coast bays"]'::jsonb,'["Private A/C vehicle & chauffeur-guide throughout","All fuel, parking, and driver accommodation","Airport pickup & drop-off","Highland railway reservations","24/7 WhatsApp support"]'::jsonb,'[{"day":"Days 1–3","title":"Negombo → Ancient Cities","detail":"Ease in on the lagoon coast, then journey through Anuradhapura''s sacred stupas and Polonnaruwa''s stone gardens by bicycle."},{"day":"Days 4–5","title":"Sigiriya & Knuckles foothills","detail":"The Lion Rock at dawn, cave temples at Dambulla and an elephant safari at Minneriya."},{"day":"Days 6–7","title":"Kandy → Tea Country","detail":"The sacred city, then climbing roads through emerald estates to a colonial-era tea bungalow in Nuwara Eliya."},{"day":"Days 8–9","title":"The Railway → Ella","detail":"The celebrated blue train through cloud forest, Nine Arch Bridge and highland hikes."},{"day":"Days 10–11","title":"Safari Country","detail":"Udawalawe''s elephant herds and Yala''s elusive leopards, with a night between the parks."},{"day":"Days 12–13","title":"The South Coast","detail":"Whales at Mirissa, snorkelling coves, and lazy afternoons behind Galle''s Dutch ramparts."},{"day":"Day 14","title":"Departure","detail":"A scenic expressway transfer back to the airport — or extend with extra beach days."}]'::jsonb,true,1) on conflict (slug) do nothing;
insert into public.tours (slug,title,category,duration,price_from,image,excerpt,highlights,includes,itinerary,featured,sort) values ('hill-country-tea-trails-5-days','Hill Country & Tea Trails','Multi-Day','5 days · 4 nights',490,'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1600&q=80','A slow, cool-climate escape through Sri Lanka''s tea heartland — waterfalls, colonial hill stations, cloud-forest hikes and the island''s most famous train ride.','["Private tea-factory tour & tasting","Horton Plains & World''s End (optional)","Kandy–Ella railway in reserved seats","Little Adam''s Peak & Nine Arch Bridge"]'::jsonb,'["Private A/C vehicle & chauffeur-guide throughout","All fuel, parking, and driver accommodation","Railway reservations","24/7 WhatsApp support"]'::jsonb,'[{"day":"Day 1","title":"Colombo → Kandy","detail":"Riverside lunch en route, spice garden stop and an evening lakeside walk in the last royal capital."},{"day":"Day 2","title":"Kandy → Nuwara Eliya","detail":"Ramboda Falls and a working tea factory, arriving into ''Little England'' for a fireside evening."},{"day":"Day 3","title":"Horton Plains","detail":"An early start across the misty plateau to World''s End''s kilometre-high cliff, afternoon at leisure."},{"day":"Day 4","title":"The Railway → Ella","detail":"The most scenic stretch of track on the island, then sunset from Little Adam''s Peak."},{"day":"Day 5","title":"Ella → Onward","detail":"Nine Arch Bridge at dawn before we deliver you to the coast, the airport or your next adventure."}]'::jsonb,false,2) on conflict (slug) do nothing;
insert into public.tours (slug,title,category,duration,price_from,image,excerpt,highlights,includes,itinerary,featured,sort) values ('wild-coast-safari-beaches-10-days','Wild Coast — Safari & Beaches','Multi-Day','10 days · 9 nights',980,'https://images.unsplash.com/photo-1456926631375-92c8ce872def?auto=format&fit=crop&w=1600&q=80','For wildlife lovers and beach dreamers: three national parks, river safaris, and a slow drift down the south coast''s most beautiful bays.','["Yala, Udawalawe & Bundala parks","Elephant Transit Home visit","Whale watching in Mirissa (Nov–Apr)","Hiriketiya, Tangalle & Unawatuna beaches"]'::jsonb,'["Private A/C vehicle & chauffeur-guide throughout","All fuel, parking, and driver accommodation","Safari jeep coordination","24/7 WhatsApp support"]'::jsonb,null,false,3) on conflict (slug) do nothing;
insert into public.tours (slug,title,category,duration,price_from,image,excerpt,highlights,includes,itinerary,featured,sort) values ('surf-soul-east-coast-8-days','Surf & Soul — East Coast','Multi-Day','8 days · 7 nights',720,'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1600&q=80','Arugam Bay season done properly — dawn patrol transfers to Main Point, Whiskey Point and Peanut Farm, with a lagoon safari and Kumana wildlife on rest days.','["Board-friendly vehicle all week","Dawn transfers to the day''s best break","Kumana National Park safari","Pottuvil lagoon mangrove tour"]'::jsonb,'["Private board-racked vehicle & driver","All fuel and parking","Flexible daily scheduling around swell","24/7 WhatsApp support"]'::jsonb,null,false,4) on conflict (slug) do nothing;
insert into public.tours (slug,title,category,duration,price_from,image,excerpt,highlights,includes,itinerary,featured,sort) values ('sigiriya-dambulla-day-tour','Sigiriya & Dambulla in a Day','Day Tour','Full day · from Colombo/Kandy/Negombo',95,'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1600&q=80','Climb the 1,600-year-old Lion Rock and wander the golden cave temples of Dambulla on a perfectly-paced private day trip.','["Sigiriya Rock Fortress climb","Dambulla cave temple complex","Traditional Sri Lankan lunch stop","Optional village catamaran ride"]'::jsonb,'["Private car & driver","Fuel & parking","Bottled water","Flexible pickup time"]'::jsonb,null,true,5) on conflict (slug) do nothing;
insert into public.tours (slug,title,category,duration,price_from,image,excerpt,highlights,includes,itinerary,featured,sort) values ('kandy-cultural-day-tour','Kandy — The Sacred City','Day Tour','Full day · from Colombo/Negombo',85,'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1600&q=80','Temples, royal gardens and highland air: the Temple of the Sacred Tooth, Peradeniya Botanical Gardens and a scenic hill-road return.','["Temple of the Sacred Tooth Relic","Royal Botanical Gardens, Peradeniya","Kandy Lake & city viewpoint","Tea factory visit en route"]'::jsonb,'["Private car & driver","Fuel & parking","Bottled water","Flexible pickup time"]'::jsonb,null,false,6) on conflict (slug) do nothing;
insert into public.tours (slug,title,category,duration,price_from,image,excerpt,highlights,includes,itinerary,featured,sort) values ('ella-nine-arch-day-tour','Ella & the Nine Arch Bridge','Day Tour','Full day · from south coast/hill country',80,'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=2200&q=80','Watch the blue train cross the jungle-wrapped Nine Arch Bridge, hike Little Adam''s Peak, and cool off at Rawana Falls.','["Nine Arch Bridge train crossing","Little Adam''s Peak sunrise hike","Rawana waterfall","Ella town café stop"]'::jsonb,'["Private car & driver","Fuel & parking","Bottled water","Flexible pickup time"]'::jsonb,null,false,7) on conflict (slug) do nothing;
insert into public.tours (slug,title,category,duration,price_from,image,excerpt,highlights,includes,itinerary,featured,sort) values ('galle-south-coast-day-tour','Galle Fort & the South Coast','Day Tour','Full day · from Colombo/south coast',75,'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1600&q=80','Cinnamon-scented lanes inside a 17th-century Dutch fort, stilt-fishermen coastline, a turtle hatchery and the day''s best beach.','["Galle Fort ramparts walk","Koggala stilt fishermen","Sea turtle hatchery visit","Sunset at Unawatuna or Dalawella"]'::jsonb,'["Private car & driver","Fuel & parking","Bottled water","Flexible pickup time"]'::jsonb,null,false,8) on conflict (slug) do nothing;
insert into public.tours (slug,title,category,duration,price_from,image,excerpt,highlights,includes,itinerary,featured,sort) values ('yala-leopard-safari','Yala Leopard Safari','Safari','Half or full day · dawn & dusk drives',110,'https://images.unsplash.com/photo-1456926631375-92c8ce872def?auto=format&fit=crop&w=1600&q=80','The world''s densest leopard population, plus elephants, sloth bears and crocodile-lined lagoons — tracked from a private 4×4 with an expert driver.','["Private jeep — never shared","Expert tracker-driver","Park permits arranged","Best-light dawn or dusk timing"]'::jsonb,'["Private 4×4 jeep","Park entrance coordination","Hotel pickup nearby","Binoculars & water"]'::jsonb,null,true,9) on conflict (slug) do nothing;
insert into public.tours (slug,title,category,duration,price_from,image,excerpt,highlights,includes,itinerary,featured,sort) values ('minneriya-elephant-gathering','Minneriya — The Gathering','Safari','Half day · afternoon drive',90,'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=1600&q=80','In season, hundreds of wild elephants converge on Minneriya''s ancient reservoir — one of Asia''s greatest wildlife spectacles, minutes from Sigiriya.','["Asia''s largest elephant gathering (Aug–Oct)","Private jeep with viewing roof","Combines perfectly with Sigiriya","Expert naturalist drivers"]'::jsonb,'["Private 4×4 jeep","Park entrance coordination","Hotel pickup nearby","Binoculars & water"]'::jsonb,null,false,10) on conflict (slug) do nothing;
insert into public.tours (slug,title,category,duration,price_from,image,excerpt,highlights,includes,itinerary,featured,sort) values ('udawalawe-elephant-safari','Udawalawe Elephant Safari','Safari','Half day · dawn or dusk',85,'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=1600&q=80','Almost guaranteed elephant encounters on open grassland beneath the highland escarpment, with a visit to the famous orphan Elephant Transit Home.','["Reliable year-round elephant herds","Elephant Transit Home feeding time","Open savannah photography","En-route stop between hills & coast"]'::jsonb,'["Private 4×4 jeep","Park entrance coordination","Hotel pickup nearby","Binoculars & water"]'::jsonb,null,false,11) on conflict (slug) do nothing;

insert into public.destinations (slug,name,region,headline,description,best_for,best_time,highlights,image,sort) values ('sigiriya','Sigiriya','Cultural Triangle','A palace in the sky, painted fifteen centuries ago','Rising two hundred metres above jungle canopy, the Lion Rock is Sri Lanka''s single most extraordinary sight — a 5th-century royal citadel of frescoes, mirror walls and water gardens. Base yourself here for Dambulla''s cave temples, Minneriya''s elephants and slow village life among the paddies.','["History","Sunrise climbs","Wildlife nearby"]'::jsonb,'Year-round · driest Jan–Sep','["Sigiriya Rock Fortress","Pidurangala sunrise viewpoint","Dambulla cave temples","Minneriya elephant gathering"]'::jsonb,'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1600&q=80',0) on conflict (slug) do nothing;
insert into public.destinations (slug,name,region,headline,description,best_for,best_time,highlights,image,sort) values ('kandy','Kandy','Hill Capital','The last royal city, wrapped around a sacred lake','Home to the Temple of the Sacred Tooth Relic and gateway to the highlands, Kandy blends devotion, colonial architecture and misty hills. Time your visit for evening puja at the temple, then lose an afternoon in the Peradeniya Royal Botanical Gardens.','["Culture","Temples","Gardens"]'::jsonb,'Dec–Apr · Esala Perahera in Jul/Aug','["Temple of the Sacred Tooth","Peradeniya Botanical Gardens","Kandy Lake loop","Highland railway departure point"]'::jsonb,'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1600&q=80',1) on conflict (slug) do nothing;
insert into public.destinations (slug,name,region,headline,description,best_for,best_time,highlights,image,sort) values ('ella','Ella','Hill Country','Cloud forests, waterfalls and the world''s prettiest railway','A laid-back mountain village strung between two peaks, Ella is hiking trails at dawn, café culture by noon and train-spotting at the Nine Arch Bridge in between. The Kandy–Ella railway finale is the most beautiful stretch of track in Asia.','["Hiking","Train rides","Café culture"]'::jsonb,'Jan–Sep','["Nine Arch Bridge","Little Adam''s Peak","Ella Rock hike","Rawana Falls"]'::jsonb,'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=2200&q=80',2) on conflict (slug) do nothing;
insert into public.destinations (slug,name,region,headline,description,best_for,best_time,highlights,image,sort) values ('nuwara-eliya','Nuwara Eliya','Tea Country','Little England, two thousand metres up','Rose gardens, Tudor cottages and lake mists — Sri Lanka''s highest town is the heart of Ceylon tea country. Tour a working factory, sip single-estate brews where they''re grown, and hike the otherworldly Horton Plains plateau to World''s End.','["Tea estates","Cool climate","Colonial charm"]'::jsonb,'Feb–May · Apr ''season'' festivities','["Tea factory tours & tastings","Horton Plains & World''s End","Gregory Lake","Ramboda & Devon Falls"]'::jsonb,'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1600&q=80',3) on conflict (slug) do nothing;
insert into public.destinations (slug,name,region,headline,description,best_for,best_time,highlights,image,sort) values ('yala','Yala','Deep South','Leopard country — the island at its wildest','Yala National Park holds the densest leopard population on Earth, sharing its lagoons and rock outcrops with elephants, sloth bears, crocodiles and painted storks. Dawn drives give the best light and sightings; we arrange private jeeps only.','["Leopards","Photography","Big wildlife"]'::jsonb,'Feb–Jul · park may close Sep–Oct','["Private dawn game drives","Leopard & sloth bear tracking","Coastal dunes & lagoons","Bundala birdlife nearby"]'::jsonb,'https://images.unsplash.com/photo-1456926631375-92c8ce872def?auto=format&fit=crop&w=1600&q=80',4) on conflict (slug) do nothing;
insert into public.destinations (slug,name,region,headline,description,best_for,best_time,highlights,image,sort) values ('galle','Galle','South Coast','A 17th-century Dutch fort, alive with cafés and craft','Inside Galle Fort''s ramparts, cinnamon-scented lanes hide boutique hotels, galleries and rooftop bars. Beyond the walls: stilt fishermen, turtle beaches, and jungle-backed bays like Unawatuna and Dalawella with its famous palm swing.','["Boutique stays","History","Beaches nearby"]'::jsonb,'Nov–Apr','["Rampart sunset walk","Dutch-era architecture","Unawatuna & Jungle Beach","Koggala stilt fishermen"]'::jsonb,'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1600&q=80',5) on conflict (slug) do nothing;
insert into public.destinations (slug,name,region,headline,description,best_for,best_time,highlights,image,sort) values ('mirissa','Mirissa','South Coast','Blue whales at breakfast, beach bonfires by night','A crescent of golden sand famous for the biggest animals that have ever lived — blue whales cruise offshore from November to April. Add Coconut Tree Hill at sunrise, snorkelling with turtles, and some of the island''s best seafood.','["Whale watching","Beach life","Seafood"]'::jsonb,'Nov–Apr','["Blue whale excursions","Coconut Tree Hill","Turtle snorkelling","Secret Beach coves"]'::jsonb,'https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=1600&q=80',6) on conflict (slug) do nothing;
insert into public.destinations (slug,name,region,headline,description,best_for,best_time,highlights,image,sort) values ('arugam-bay','Arugam Bay','East Coast','One of the world''s great right-hand point breaks','From May to September the east coast wakes up: Main Point peels for hundreds of metres, and a barefoot village of surf camps and juice bars hums beneath the palms. Rest days mean lagoon safaris, Kumana''s wild elephants and empty golden beaches.','["Surfing","Beach village vibes","East-coast season"]'::jsonb,'May–Sep','["Main Point & Whiskey Point","Peanut Farm & Elephant Rock","Kumana National Park","Pottuvil lagoon safari"]'::jsonb,'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1600&q=80',7) on conflict (slug) do nothing;
insert into public.destinations (slug,name,region,headline,description,best_for,best_time,highlights,image,sort) values ('colombo','Colombo','Western Capital','Temples, tuk-tuks and a fast-rising food scene','Most journeys begin or end in the capital — give it a day. Colonial-era Fort and Pettah''s bazaars, Gangaramaya Temple, Galle Face Green at sunset, and a dinner scene that now rivals any city in South Asia.','["City culture","Food","First/last nights"]'::jsonb,'Year-round','["Gangaramaya Temple","Pettah markets","Galle Face sunset","Independence Square"]'::jsonb,'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=1600&q=80',8) on conflict (slug) do nothing;

insert into public.services (slug,name,tagline,description,image,icon,sort) values ('airport-transfers','Airport Transfers','Land softly. We''re already waiting.','Meet-and-greet at Bandaranaike International with a name board, cold water and air-conditioned comfort. Fixed prices, flight tracking, and a driver who knows exactly where your hotel is — day or night.','https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=1600&q=80','plane',0) on conflict (slug) do nothing;
insert into public.services (slug,name,tagline,description,image,icon,sort) values ('private-driver-hire','Private Driver Hire','Your own chauffeur-guide, for as long as you need.','Hire a professional English-speaking chauffeur for a day, a week or your entire holiday. Your driver handles routes, tickets, restaurants and local knowledge while you simply enjoy the island.','https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=1600&q=80','steering',1) on conflict (slug) do nothing;
insert into public.services (slug,name,tagline,description,image,icon,sort) values ('taxi-services','Taxi Services','Point to point, without the haggling.','Reliable, fairly-priced private taxis between any two points in Sri Lanka. Transparent quotes upfront, clean modern vehicles, and drivers who arrive on time, every time.','https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1600&q=80','car',2) on conflict (slug) do nothing;
insert into public.services (slug,name,tagline,description,image,icon,sort) values ('day-tours','Day Tours','One perfect day, expertly arranged.','Sigiriya at sunrise, Galle Fort at golden hour, Kandy''s temples, Ella''s bridges. Private day tours from wherever you''re staying, paced entirely around you.','https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1600&q=80','sun',3) on conflict (slug) do nothing;
insert into public.services (slug,name,tagline,description,image,icon,sort) values ('multi-day-tours','Multi-Day Tours','The whole island, woven into one journey.','From five-day highlights to grand three-week circuits — beaches, tea country, ancient cities and safaris connected by one trusted driver and a route built around your interests.','https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=2200&q=80','map',4) on conflict (slug) do nothing;
insert into public.services (slug,name,tagline,description,image,icon,sort) values ('safari-tours','Safari Tours','Leopards, elephants and wild dawns.','Private jeep safaris in Yala, Udawalawe, Wilpattu and Minneriya with experienced trackers. We arrange park permits, the right jeep, and the timing that gives you the best sightings.','https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1600&q=80','binoculars',5) on conflict (slug) do nothing;
insert into public.services (slug,name,tagline,description,image,icon,sort) values ('surf-transfers','Surf Transfers','Boards on the roof, swell on the horizon.','Board-friendly vehicles and drivers who understand dawn patrol. Airport to Arugam Bay, Weligama to Hiriketiya — we move surfers and their quivers safely, all season long.','https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1600&q=80','waves',6) on conflict (slug) do nothing;
insert into public.services (slug,name,tagline,description,image,icon,sort) values ('hotel-transfers','Hotel Transfers','Seamless links between every stay.','Comfortable private transfers between hotels, villas and boutique stays anywhere on the island — with scenic stops, luggage handled, and zero stress between check-outs and check-ins.','https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1600&q=80','hotel',7) on conflict (slug) do nothing;
insert into public.services (slug,name,tagline,description,image,icon,sort) values ('custom-itineraries','Custom Travel Itineraries','Designed around you, down to the last sunset.','Tell us your dates, pace and dreams — honeymoon, family adventure, photography trip — and we''ll design a bespoke route with hand-picked stays, experiences and a dedicated driver.','https://images.unsplash.com/photo-1505142468610-359e7d316be0?auto=format&fit=crop&w=1600&q=80','route',8) on conflict (slug) do nothing;

insert into public.vehicles (slug,name,category,passengers,luggage,features,ideal_for,image,sort) values ('executive-sedan','Executive Sedan','Comfort · up to 3 guests',3,'2 large + 2 cabin','["Full air-conditioning","Reclining leather seats","USB charging & Wi-Fi hotspot","Complimentary bottled water"]'::jsonb,'Couples, business travellers and airport transfers.','https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1600&q=80',0) on conflict (slug) do nothing;
insert into public.vehicles (slug,name,category,passengers,luggage,features,ideal_for,image,sort) values ('premium-suv','Premium SUV','Luxury · up to 4 guests',4,'3 large + 2 cabin','["Elevated seating & panoramic views","Dual-zone climate control","Extra legroom for long routes","Child seats on request"]'::jsonb,'Families and hill-country roads in complete comfort.','https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1600&q=80',1) on conflict (slug) do nothing;
insert into public.vehicles (slug,name,category,passengers,luggage,features,ideal_for,image,sort) values ('high-roof-van','High-Roof Van (KDH)','Group · up to 8 guests',8,'6 large + surfboards','["Captain-style seating","Powerful rear A/C","Roof racks for boards & gear","Cooler box on request"]'::jsonb,'Small groups, surf trips and multi-day circuits.','https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=1600&q=80',2) on conflict (slug) do nothing;
insert into public.vehicles (slug,name,category,passengers,luggage,features,ideal_for,image,sort) values ('mini-coach','Mini Coach','Groups · up to 22 guests',22,'Full luggage hold','["Reclining coach seats","PA system for guides","Large windows for sightseeing","Experienced long-route drivers"]'::jsonb,'Wedding parties, retreats and larger tour groups.','https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=1600&q=80',3) on conflict (slug) do nothing;
insert into public.vehicles (slug,name,category,passengers,luggage,features,ideal_for,image,sort) values ('safari-jeep','Safari Jeep 4×4','Wild · up to 6 guests',6,'Day packs & camera gear','["Open-top game-viewing design","Experienced tracker-drivers","Park permits arranged","Binoculars provided"]'::jsonb,'Yala, Udawalawe, Wilpattu and Minneriya safaris.','https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1600&q=80',4) on conflict (slug) do nothing;

insert into public.reviews (name,country,trip,rating,text,sort) values ('Charlotte & James','United Kingdom','14-day Grand Island Circuit',5,'From the moment we landed to our final sunset in Galle, everything was flawless. Our driver felt like a friend who happened to know every hidden corner of Sri Lanka. The best travel decision we''ve ever made.',0);
insert into public.reviews (name,country,trip,rating,text,sort) values ('Mia Lindqvist','Sweden','Surf transfers, Arugam Bay season',5,'Boards handled with care, 4 a.m. starts with a smile, and always on time. Island Route moved our whole crew across the island twice. Wouldn''t trust anyone else with a quiver.',1);
insert into public.reviews (name,country,trip,rating,text,sort) values ('The Fischer Family','Germany','10-day family tour with safari',5,'Travelling with two young kids, we needed patience and flexibility — we got both, plus child seats, snack stops and a leopard sighting in Yala the children will never forget.',2);
insert into public.reviews (name,country,trip,rating,text,sort) values ('Aiko & Kenji','Japan','Honeymoon — custom itinerary',5,'They designed our honeymoon around tea country sunrises and quiet beaches. Every hotel pickup was seamless and the private candlelit dinner surprise in Ella made the trip.',3);
insert into public.reviews (name,country,trip,rating,text,sort) values ('Daniel O''Connor','Australia','Airport transfer + Kandy day tour',5,'Flight landed three hours late — driver was still there, name board up, zero fuss. The next day''s Kandy tour was superb. Professional outfit from start to finish.',4);
insert into public.reviews (name,country,trip,rating,text,sort) values ('Sophie Moreau','France','7-day Essential Sri Lanka',5,'Impeccable vehicle, thoughtful pacing, and a driver-guide whose knowledge of history and food elevated everything. Sri Lanka is stunning; Island Route made it effortless.',5);
insert into public.reviews (name,country,trip,rating,text,sort) values ('Ravi & Priya Patel','United States','Hill Country & Tea Trails',5,'The train-and-car combination through the highlands was genius — we rode the famous blue train while our luggage travelled ahead. Five stars isn''t enough.',6);
insert into public.reviews (name,country,trip,rating,text,sort) values ('Emma Verhoeven','Netherlands','Solo traveller — 12 days',5,'As a solo female traveller, safety was my priority. I felt completely looked after the entire trip, with total freedom to change plans. Absolutely recommend.',7);

insert into public.posts (slug,title,excerpt,date,read_time,image,sections) values ('ultimate-10-day-sri-lanka-itinerary','The Ultimate 10-Day Sri Lanka Itinerary','Ancient rocks, the famous blue train, leopards and a beach finale — how to see the best of the island in ten unhurried days.','2026-06-12','8 min read','https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=2200&q=80','[{"body":"Ten days is the sweet spot for a first visit to Sri Lanka: enough time to link the Cultural Triangle, the tea highlands and the southern coast without ever feeling rushed. Here''s the route we recommend to most first-time guests, refined over hundreds of journeys."},{"heading":"Days 1–3: The Cultural Triangle","body":"Land, recover, and head straight for Sigiriya. Climb the Lion Rock at dawn before the heat and the crowds, explore Dambulla''s painted caves, and if you''re travelling between August and October, don''t miss the elephant gathering at Minneriya — hundreds of wild elephants around a single ancient reservoir."},{"heading":"Days 4–5: Kandy and the climb to tea country","body":"Kandy deserves a slow afternoon: the Temple of the Sacred Tooth at evening puja, then the lakeside as the town lights come on. The next morning, wind upward through waterfalls and tea terraces to Nuwara Eliya, stopping at a working factory to taste estate tea at its source."},{"heading":"Days 6–7: The railway and Ella","body":"The Nanu Oya to Ella stretch is the most beautiful train ride in Asia — reserve seats and let your driver carry the luggage ahead. In Ella, hike Little Adam''s Peak for sunrise and watch the train cross the Nine Arch Bridge from a jungle café."},{"heading":"Days 8–9: Safari and the south","body":"Drop out of the hills to Yala for a dawn game drive — the world''s best odds of a wild leopard sighting — then follow the coast west through Tangalle and Mirissa. In season, a blue whale excursion is unforgettable."},{"heading":"Day 10: Galle and departure","body":"End inside Galle Fort''s 17th-century ramparts with breakfast on a rooftop, a last swim at Unawatuna, and an easy expressway run to the airport. Ten days, one island, zero regrets."}]'::jsonb) on conflict (slug) do nothing;
insert into public.posts (slug,title,excerpt,date,read_time,image,sections) values ('when-to-visit-sri-lanka','When to Visit Sri Lanka: A Season-by-Season Guide','Two monsoons mean there''s always a sunny coast somewhere. Here''s how to time beaches, safaris, surf and the highlands perfectly.','2026-05-02','6 min read','https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=2000&q=80','[{"body":"The most common question we get is ''when is the best time to visit Sri Lanka?'' The honest answer: almost any month — if you pick the right coast. The island sits between two monsoon systems, so while one shore takes rain, the opposite one is at its best."},{"heading":"December to April: the classic season","body":"The west and south coasts — Bentota, Galle, Mirissa, Tangalle — enjoy blue skies and calm seas. This is peak whale-watching season in Mirissa and the ideal window for the classic Cultural Triangle plus southern beaches route. Book early for Christmas and New Year."},{"heading":"May to September: the east awakens","body":"As the southwest monsoon arrives, the action shifts east. Arugam Bay''s famous right-handers fire, Trincomalee and Pasikudah offer glassy seas, and Kumana''s lagoons teem with birdlife. This is our favourite ''secret season'' — fewer crowds, golden light."},{"heading":"Safari timing","body":"Yala is at its best February through July as water sources shrink and wildlife concentrates; note the park often closes for several weeks around September–October. Minneriya''s great elephant gathering peaks August to October. Udawalawe delivers elephants reliably all year."},{"heading":"The highlands","body":"Tea country is gorgeous year-round, with January to March offering the clearest mountain views. Pack a warm layer whatever the month — Nuwara Eliya evenings are properly cool at 1,900 metres."}]'::jsonb) on conflict (slug) do nothing;
insert into public.posts (slug,title,excerpt,date,read_time,image,sections) values ('yala-vs-wilpattu-safari','Yala vs Wilpattu: Which Safari Should You Choose?','Sri Lanka''s two great national parks offer very different wild experiences. Our drivers'' honest guide to choosing between them.','2026-03-18','5 min read','https://images.unsplash.com/photo-1456926631375-92c8ce872def?auto=format&fit=crop&w=1600&q=80','[{"body":"Both parks hold healthy leopard populations and both can deliver the safari of a lifetime — but they feel completely different. After a thousand game drives between them, here''s how we advise our guests."},{"heading":"Choose Yala for density","body":"Yala Block 1 has the highest leopard density on the planet, plus elephants, sloth bears and spectacular coastal scenery where dunes meet jungle. The trade-off is popularity: in high season, a big sighting can draw a queue of jeeps. Going at dawn with an experienced tracker-driver — and avoiding weekends — makes all the difference."},{"heading":"Choose Wilpattu for wilderness","body":"Wilpattu, Sri Lanka''s largest park, is a maze of forest and natural lakes called villus. Sightings take more patience, but you''ll often have a leopard entirely to yourself, framed by ancient trees rather than other vehicles. For photographers and second-time visitors, it''s magic."},{"heading":"Or do what we do","body":"Combine one with Udawalawe. Elephants are near-guaranteed there year-round, which takes the pressure off, letting you enjoy Yala or Wilpattu as a pure leopard hunt. Many of our 10–14 day routes thread exactly this pairing."}]'::jsonb) on conflict (slug) do nothing;
insert into public.posts (slug,title,excerpt,date,read_time,image,sections) values ('south-coast-beach-guide','Sri Lanka''s South Coast: The Insider Beach Guide','From boutique bays to barefoot surf coves — where to swim, stay and watch the sunset between Galle and Tangalle.','2026-01-25','7 min read','https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=1600&q=80','[{"body":"The 80 kilometres of coastline east of Galle hold an absurd concentration of beautiful beaches, each with its own personality. Here''s how our drivers describe them to guests on the coastal road."},{"heading":"Unawatuna & Dalawella","body":"Closest to Galle Fort and great for families: calm, reef-protected swimming, the famous Dalawella palm swing and jungle-backed ''Jungle Beach'' a short scramble away. Sunset from the pagoda viewpoint is superb."},{"heading":"Weligama & Mirissa","body":"Weligama''s long, forgiving beach break is the island''s best place to learn to surf. Next door, Mirissa pairs whale watching with a proper beach-bar evening scene. Come early to Coconut Tree Hill for photos without the crowds."},{"heading":"Hiriketiya & Dickwella","body":"''Hiri'' is the south''s darling — a tiny horseshoe bay of jungle, longboard peelers and specialty coffee. It gets busy in season; nearby Dickwella carries the overflow with a broader sweep of sand."},{"heading":"Tangalle and beyond","body":"Keep driving east and the crowds fall away. Tangalle''s wild, golden beaches front some of the island''s loveliest boutique hotels, and by Rekawa, you''re sharing the sand mainly with nesting sea turtles. This is where we send honeymooners."}]'::jsonb) on conflict (slug) do nothing;

insert into public.gallery (src,caption,category,sort) values ('https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=2200&q=80','The iconic highland railway, Ella','Journeys',0);
insert into public.gallery (src,caption,category,sort) values ('https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=2000&q=80','South coast, early morning','Beaches',1);
insert into public.gallery (src,caption,category,sort) values ('https://images.unsplash.com/photo-1456926631375-92c8ce872def?auto=format&fit=crop&w=1600&q=80','Leopard, Yala National Park','Wildlife',2);
insert into public.gallery (src,caption,category,sort) values ('https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1600&q=80','Dawn mist over tea country','Hills',3);
insert into public.gallery (src,caption,category,sort) values ('https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1600&q=80','Sigiriya — the Lion Rock','Culture',4);
insert into public.gallery (src,caption,category,sort) values ('https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1600&q=80','Reef break, east coast season','Surf',5);
insert into public.gallery (src,caption,category,sort) values ('https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=1600&q=80','The Gathering, Minneriya','Wildlife',6);
insert into public.gallery (src,caption,category,sort) values ('https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=1600&q=80','Palm-fringed shoreline, Mirissa','Beaches',7);
insert into public.gallery (src,caption,category,sort) values ('https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1600&q=80','Sacred city of Kandy','Culture',8);
insert into public.gallery (src,caption,category,sort) values ('https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=80','The road to Nuwara Eliya','Hills',9);
insert into public.gallery (src,caption,category,sort) values ('https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1600&q=80','Sea turtle, Hikkaduwa reef','Wildlife',10);
insert into public.gallery (src,caption,category,sort) values ('https://images.unsplash.com/photo-1468413253725-0d5181091126?auto=format&fit=crop&w=1600&q=80','Last light, west coast','Beaches',11);

insert into public.site_settings (key,value) values ('site_name','Island Route Sri Lanka') on conflict (key) do update set value = excluded.value;
insert into public.site_settings (key,value) values ('tagline','Private journeys across the pearl of the Indian Ocean') on conflict (key) do update set value = excluded.value;
insert into public.site_settings (key,value) values ('phone_display','+94 77 801 0391') on conflict (key) do update set value = excluded.value;
insert into public.site_settings (key,value) values ('phone_e164','+94778010391') on conflict (key) do update set value = excluded.value;
insert into public.site_settings (key,value) values ('whatsapp_number','94778010391') on conflict (key) do update set value = excluded.value;
insert into public.site_settings (key,value) values ('email','islandroutesrilanka@gmail.com') on conflict (key) do update set value = excluded.value;
insert into public.site_settings (key,value) values ('address','Colombo, Sri Lanka') on conflict (key) do update set value = excluded.value;
insert into public.site_settings (key,value) values ('seo_title','Island Route Sri Lanka — Private Tours, Transfers & Tailor-Made Journeys') on conflict (key) do update set value = excluded.value;
insert into public.site_settings (key,value) values ('seo_description','Island Route Sri Lanka crafts private, chauffeur-driven journeys across Sri Lanka — airport transfers, day tours, safaris, surf trips and tailor-made multi-day itineraries with trusted English-speaking drivers.') on conflict (key) do update set value = excluded.value;
insert into public.site_settings (key,value) values ('seo_keywords','Sri Lanka tours, Sri Lanka private driver, Colombo airport transfer, Yala safari, Sri Lanka tour packages') on conflict (key) do update set value = excluded.value;

-- Example drivers (edit in the admin dashboard)
insert into public.drivers (name,phone,languages) select 'Gayan','+94778010391','["English","Sinhala"]'::jsonb where not exists (select 1 from public.drivers where name = 'Gayan');
insert into public.drivers (name,phone,languages) select 'Nuwan','+94770000001','["English","Sinhala","German"]'::jsonb where not exists (select 1 from public.drivers where name = 'Nuwan');
insert into public.drivers (name,phone,languages) select 'Kasun','+94770000002','["English","Sinhala"]'::jsonb where not exists (select 1 from public.drivers where name = 'Kasun');
